model_organization: <the github organization that this model appears>
model_name: <the name of the github repository (e.g. my-repository)>
root_schema: <the name of the base schema file (w/o .yaml) (e.g. sample)>
model_root_class: <name of the base class in the schema for loader testing (e.g. Person)>

model_author: <your name>
model_author_email: <your email>
model_synopsis: <one liner about the model>
model_description: |-
  <in depth description of the model>

# Trove Classifiers (https://pypi.org/classifiers/) -- if omitted there are reasonable defaults
classifiers:
    - "Development Status :: 4 - Beta"
    - "Environment :: Console"
    - "Intended Audience :: Developers"
    - "Intended Audience :: Science/Research"
    - "Intended Audience :: Information Technology"
    - "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication"
    - "Programming Language :: Python :: 3 :: Only"
    - "Programming Language :: Python :: 3.7"
    - "Programming Language :: Python :: 3.8"
    - "Programming Language :: Python :: 3.9"

# Keywords -- if omitted, there are reasonable defaults
keywords: [linkml, LOD, Modeling, Linked open data, model]

# Elements to be generated
# See: https://github.com/linkml/linkml/generators/README.md for what the outputs look like
# Possible values: graphql -- graphql schema for the model
#                  json -- LinkML model definition in JSON syntax
#                  jsonld_context -- JSON-LD context definitions for model
#                  json_schema -- Model schema in json schema
#                  owl -- OWL representation of model schema
#                  rdf -- LinkML Model definition in RDF
#                  shex -- LinkML model definition in ShEx
#                  sqlddl -- SQL ddl of the model
#                  model -- copy model/schema to distribution directory
generate: [jsonld_context, json_schema, model]

